application: pokequiz
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /images
  static_dir: static/images
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
  - ^node_modules/(.*/)?
  - ^venv/(.*/)?
  - ^(.*/)?.*\.py[co]$